config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'homes#index'
  resources :homes, only:[:index]
    namespace :admin do
      resources :homes, only: [:index, :new, :create, :show,  :edit, :update, :destroy]
  end


  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'   
} 

# root  'inquiry#index'
  # get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiries/confirm' => 'inquiries#confirm'   # 確認画面
  post  'inquiries/back' => 'inquiries#back'   # 確認画面
  post  'inquiries/thanks'  => 'inquiries#thanks'    # 送信完了画面

  get  'iihomes/youtube'  => 'iihomes#youtube'    # 送信完了画面
  get  'eehomes/youtube'  => 'eehomes#youtube'    # 送信完了画面



# resources :users, :only => [:show]

resource :ahomes, only:[:edit,:update]

resource :bhomes, only:[:edit,:update]

resource :chomes, only:[:edit,:update]

resource :dhomes, only:[:edit,:update]

resource :ehomes, only:[:update]

resource :ehomes, only:[:new,:create,:update]

resource :fhomes, only:[:update]

resource :ihomes, only:[:update] 


  

resource :contacts, only:[:update]

resource :interviews, only:[:update]


resource :blogs, only:[:new,:create,:destroy,:update]

# devise_scope :user do
#   get "user/:id", :to => "users/registrations#detail"
#   get "signup", :to => "users/registrations#new"
#   get "login", :to => "users/sessions#new"
#   get "logout", :to => "users/sessions#destroy"
# end

end

app/models/aahome.rb
class Aahome < ApplicationRecord
  belongs_to :ahome
  
end

app/models/ahome.rb
class Ahome < ApplicationRecord
  has_many :aahomes
  accepts_nested_attributes_for :aahomes,allow_destroy: true
  mount_uploader :logo, ImageUploader
end

app/models/bbhome.rb
class Bbhome < ApplicationRecord
  belongs_to :bhome
  mount_uploader :image, ImageUploader
end

app/models/bhome.rb
class Bhome < ApplicationRecord
  has_many :bbhomes
  accepts_nested_attributes_for :bbhomes,allow_destroy: true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_rich_text :content
  mount_uploader :image, ImageUploader
end

app/models/chome.rb
class Chome < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/dhome.rb
class Dhome < ApplicationRecord
end

app/models/eehome.rb
class Eehome < ApplicationRecord
  belongs_to :ehome
  # mount_uploader :image, VideoUploader
  mount_uploader :image, ImageUploader

end

app/models/ehome.rb
class Ehome < ApplicationRecord
  has_many :eehomes
  accepts_nested_attributes_for :eehomes,allow_destroy: true
end

app/models/ffhome.rb
class Ffhome < ApplicationRecord
  belongs_to :fhome
end

app/models/fhome.rb
class Fhome < ApplicationRecord
  has_many :ffhomes
  accepts_nested_attributes_for :ffhomes,allow_destroy: true
end

app/models/home.rb
class Home < ApplicationRecord
  has_many :interviews
  accepts_nested_attributes_for :interviews,allow_destroy: true
end

app/models/ihome.rb
class Ihome < ApplicationRecord
  has_many :iihomes
  accepts_nested_attributes_for :iihomes,allow_destroy: true
end

app/models/iihome.rb
class Iihome < ApplicationRecord
  belongs_to :ihome
  mount_uploader :image, ImageUploader
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  # attr_accessor :name, :email, :message

  validates :name,presence: { :message => 'ご担当者様名を入力してください。'}
  validates :email,presence: { :message => 'E-mailを入力してください。'}
  validates :message,presence: { :message => 'お問い合わせ内容を入力してください'}
end

app/models/interview.rb
class Interview < ApplicationRecord
  belongs_to :home
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # devise :database_authenticatable, :rememberable, :validatable
end

app/controllers/ahomes_controller.rb
class AhomesController < ApplicationController
  before_action :if_not_admin
  # def new

    

  # end

  # def edit
  #   @ahomes = Ahome.find(params[:id])

  # end

  def update
    @ahomes = Ahome.find(params[:id])
    @msg = "アップデートが完了しました。"
    @ahomes.update(ahomes_params)
    #   redirect_to request.referer
    # else
    #   render :new
    # end
  end

  private 
  def if_not_admin
    if user_signed_in?
      redirect_to root_path unless current_user.admin?
    else
      redirect_to root_path
    end
  end

  def ahomes_params 


      params.require(:ahome).permit(:title,:title2,:discribe,:button_right,:button_left,:url_right,:url_left,:logo,:adress,aahomes_attributes:[:menu,:mainmenu,:id])
  
  
  end
  
  
end

app/helpers/ahomes_helper.rb
module AhomesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ahomes/_admins_ahomes.html.haml
.ahomes_secondary
  FirstPageの編集
=form_with model:ahomes, url: ahomes_path(id:ahomes.id),method: :patch,remote:true do |f|
  .ahomes__form
    .ahomes__title.aformd__title
      .formtitles
        上段のタイトル
      = f.text_field :title, class: "ahomes__title__field aformd",autocomplete: "off",placeholder:"上段のタイトルを入力してください",id:"js-ahome-edit-#{@ahomes.id}"
    .ahomes__title2.aformd__title
      .formtitles
        下段のタイトル
      = f.text_field :title2, class: "ahomes__title2__field aformd",autocomplete: "off",placeholder:"下段のタイトルを入力してください",id:"js-ahome-edit-#{@ahomes.id}"
    .ahomes__title2.aformd__title
      .formtitles
        詳細
      = f.text_field :discribe, class: "ahomes__title2__field aformd",autocomplete: "off",placeholder:"下段のタイトルを入力してください",id:"js-ahome-edit-#{@ahomes.id}"

    .ahomes__title2.aformd__title
      .formtitles
        左側のボタン名
      = f.text_field :button_left, class: "ahomes__title2__field aformd",autocomplete: "off",placeholder:"下段のタイトルを入力してください",id:"js-ahome-edit-#{@ahomes.id}"
    
    .ahomes__title2.aformd__title
      .formtitles
        右側のボタン名
      = f.text_field :button_right, class: "ahomes__title2__field aformd",autocomplete: "off",placeholder:"下段のタイトルを入力してください",id:"js-ahome-edit-#{@ahomes.id}"
    
    .ahomes__title2.aformd__title
      .formtitles
        ボタンに関連するリンク
      左側
      = f.collection_select(:url_left, ahomes.aahomes, :link, :menu)

      右側
      = f.collection_select(:url_right, ahomes.aahomes, :link, :menu)
    
    -# .ahomes__header__logo.aformd__title
    -#   .formtitles
    -#     ロゴ
    -#   = f.file_field :logo
    
    .ahomes__footer__adress.aformd__title
      .formtitles
        住所
      = f.text_field :adress, class: "ahomes__title2__field aformd"
    
  .ahomes__header__menu
    = f.fields_for :aahomes do |c|
      -# = render "bbhomes_fields", f: c
      -# - @bhomes.bbhomes.each do |d|
      .form-group
        .aformd__title
          .formtitles
            = c.label :mainmenu
            
            
        
          = c.text_field :mainmenu, class: "ahomes__title2__field aformd"
      .form-group
        .aformd__title
          .formtitles
            = c.label :menu
            
            
        
          = c.text_field :menu, class: "ahomes__title2__field aformd"
      .supless
      
      



    .ahomes__submit
      = f.submit "更新",class:"aformd__submit a1submits","data-submit-id" => "#{ahomes.id}"



.cr-edit-button.aformd__edit__button{id: "cr-edit-button#{ahomes.id}", :style => "display: none;"}
  .aaaaa.cr-cancel-button{"data-cancel-id" => "#{ahomes.id}"}
    =icon("far","times-circle")
    


-# .TopContents__ahomes__edit
-# .TopContents__ahomes__edit__button{"data-ahomes__id": "#{ahomes.id}"}
-#   = icon("fas","edit")
-#   編集する

app/views/ahomes/_ahomes.html.haml
.TopContents__container__message
  = ahomes.title
  %br
  = ahomes.title2
.TopContents__container__message2
  = ahomes.discribe
.TopContents__container__button
  .TopContents__container__button__left
    -# = link_to destroy_user_session_path, method: :delete , class:"homes__button__left" do
    =link_to "#{ahomes.url_left}", class:"homes__button__left" do
      = ahomes.button_left
  


  .TopContents__container__button__right
    = link_to "#{ahomes.url_right}" , class:"homes__button__right" do
      = ahomes.button_right

app/views/ahomes/_header__down.html.haml
.header__down__adress
  Adress
  =":"
  = ahomes.adress

app/views/ahomes/update.js.erb
$('#ahomes_area--box2-<%= @ahomes.id %>').html("<%= j(render partial: 'ahomes/ahomes', locals: {ahomes: @ahomes}) %>");
$('#ahomes_area--box3-<%= @ahomes.id %>').html("<%= j(render partial: 'ahomes/admins_ahomes', locals: {ahomes: @ahomes}) %>");

$('#header__down').html("<%= j(render partial: 'ahomes/header__down', locals: {ahomes: @ahomes}) %>");

$('#ahomes_area--box3-<%= @ahomes.id%>').hide();
$('#cr-edit-button<%= @ahomes.id%>').hide;
  $(".allcover__sheet").css("display","none");
$('#alert-message').html('<div class="alert alert-success"><%= @msg %></div>')

$("#alert-message").fadeIn().queue(function() {
            setTimeout(function(){$("#alert-message").dequeue();
            }, 5000);
        });

        $("#alert-message").fadeOut();