config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'homes#index'
  resources :homes, only:[:index]
    namespace :admin do
      resources :homes, only: [:index, :new, :create, :show,  :edit, :update, :destroy]
  end


  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'   
} 

# root  'inquiry#index'
  # get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiries/confirm' => 'inquiries#confirm'   # 確認画面
  post  'inquiries/back' => 'inquiries#back'   # 確認画面
  post  'inquiries/thanks'  => 'inquiries#thanks'    # 送信完了画面

  get  'iihomes/youtube'  => 'iihomes#youtube'    # 送信完了画面
  get  'eehomes/youtube'  => 'eehomes#youtube'    # 送信完了画面



# resources :users, :only => [:show]

resource :ahomes, only:[:edit,:update]

resource :bhomes, only:[:edit,:update]

resource :chomes, only:[:edit,:update]

resource :dhomes, only:[:edit,:update]

resource :ehomes, only:[:update]

resource :ehomes, only:[:new,:create,:update]

resource :fhomes, only:[:update]

resource :ihomes, only:[:update] 


  

resource :contacts, only:[:update]

resource :interviews, only:[:update]


resource :blogs, only:[:new,:create,:destroy,:update]

# devise_scope :user do
#   get "user/:id", :to => "users/registrations#detail"
#   get "signup", :to => "users/registrations#new"
#   get "login", :to => "users/sessions#new"
#   get "logout", :to => "users/sessions#destroy"
# end

end

app/models/aahome.rb
class Aahome < ApplicationRecord
  belongs_to :ahome
  
end

app/models/ahome.rb
class Ahome < ApplicationRecord
  has_many :aahomes
  accepts_nested_attributes_for :aahomes,allow_destroy: true
  mount_uploader :logo, ImageUploader
end

app/models/bbhome.rb
class Bbhome < ApplicationRecord
  belongs_to :bhome
  mount_uploader :image, ImageUploader
end

app/models/bhome.rb
class Bhome < ApplicationRecord
  has_many :bbhomes
  accepts_nested_attributes_for :bbhomes,allow_destroy: true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_rich_text :content
  mount_uploader :image, ImageUploader
end

app/models/chome.rb
class Chome < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/dhome.rb
class Dhome < ApplicationRecord
end

app/models/eehome.rb
class Eehome < ApplicationRecord
  belongs_to :ehome
  # mount_uploader :image, VideoUploader
  mount_uploader :image, ImageUploader

end

app/models/ehome.rb
class Ehome < ApplicationRecord
  has_many :eehomes
  accepts_nested_attributes_for :eehomes,allow_destroy: true
end

app/models/ffhome.rb
class Ffhome < ApplicationRecord
  belongs_to :fhome
end

app/models/fhome.rb
class Fhome < ApplicationRecord
  has_many :ffhomes
  accepts_nested_attributes_for :ffhomes,allow_destroy: true
end

app/models/home.rb
class Home < ApplicationRecord
  has_many :interviews
  accepts_nested_attributes_for :interviews,allow_destroy: true
end

app/models/ihome.rb
class Ihome < ApplicationRecord
  has_many :iihomes
  accepts_nested_attributes_for :iihomes,allow_destroy: true
end

app/models/iihome.rb
class Iihome < ApplicationRecord
  belongs_to :ihome
  mount_uploader :image, ImageUploader
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  # attr_accessor :name, :email, :message

  validates :name,presence: { :message => 'ご担当者様名を入力してください。'}
  validates :email,presence: { :message => 'E-mailを入力してください。'}
  validates :message,presence: { :message => 'お問い合わせ内容を入力してください'}
end

app/models/interview.rb
class Interview < ApplicationRecord
  belongs_to :home
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # devise :database_authenticatable, :rememberable, :validatable
end

app/controllers/ihomes_controller.rb
class IhomesController < ApplicationController
  def update
    @ihomes = Ihome.find(1)
    # @bbhomes = @bhomes.bbhomes
    @msg = "アップデートが完了しました。"
    @ihomes.update(ihomes_params)
    
    # if @ihomes.save
    #   redirect_to request.referer
    # else
    #   render :new
    # end
  end

  private 
  def if_not_admin
    if user_signed_in?
      redirect_to root_path unless current_user.admin?
    else
      redirect_to root_path
    end
  end

  def ihomes_params 


      # params.require(:bhome).permit(:title,:title2,:discribe,bbhomes_attributes:[:title,:discribe,:id])
      params.require(:ihome).permit(:title,:title2,:title3,iihomes_attributes:[:title,:discribe,:colum1,:colum2,:colum3,:price,:image,:youtube,:id,:_destroy])


  
  
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/ihomes_helper.rb
module IhomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ihomes/_admins_ihomes.html.haml
.ahomes_secondary
  fourthPageの編集

=form_with model: ihomes,url:ihomes_path,method: :patch, remote:true do |f|
  .ahomes__form
    .ahomes__title.aformd__title
      .formtitles
        上段のタイトル
      
      = f.text_field :title, class: "ihomes__title__field aformd",autocomplete: "off",placeholder:"上段のタイトルを入力してください",id:"js-ihome-edit-#{ihomes.id}"

    .ahomes__title.aformd__title
      .formtitles
        中段のタイトル
      = f.text_field :title2, class: "ihomes__title__field aformd",autocomplete: "off",placeholder:"上段のタイトルを入力してください",id:"js-ihome-edit-#{ihomes.id}"
    
    .ahomes__title.aformd__title
      .formtitles
        下段のタイトル
      = f.text_field :title3, class: "ihomes__title__field aformd",autocomplete: "off",placeholder:"上段のタイトルを入力してください",id:"js-ihome-edit-#{ihomes.id}"
    
    
    
  = f.fields_for :iihomes do |c|       
    .form-group
      = render 'iihome_fields', f: c

  .links.nested-fields__button2
    = link_to_add_association '追加する' ,f, :iihomes
  -# - end
      
      -# .aformd__title
      -#   .formtitles
      -#     = c.label :discribe
      -#   = c.text_field :discribe,class:"aformd"
      -# .aformd__title
      -#   .formtitles
      -#     = c.label :colum1
      -#   = c.text_field :colum1,class:"aformd"
      
      -# .aformd__title
      -#   .formtitles
      -#     = c.label :colum2
      -#   = c.text_field :colum2,class:"aformd"
      
      -# .aformd__title
      -#   .formtitles
      -#     = c.label :colum3
      -#   = c.text_field :colum3,class:"aformd"
      
      -# .aformd__title
      -#   .formtitles
      -#     = c.label :praice
      -#   = c.text_field :price,class:"aformd"
      
      

  
      
    
  .ahomes__submit
    = f.submit "更新",class:"aformd__submit"

.icr-edit-button.aformd__edit__button{id: "icr-edit-button#{ihomes.id}", :style => "display: none;"}
  .aaaaa.icr-cancel-button{"data-cancel-idi" => "#{ihomes.id}"}
    = icon("far","times-circle")

app/views/ihomes/_ihomes.html.haml
.sectionboxG__grid
  -# .sectionboxG__grid__up

  -#   .price__discribe
  -#     = ihomes.title
  -#     %br
  -#     = ihomes.title2
  -#     %br
  -#     = ihomes.title3
  .interviews__ibox
    .interviews__title
      = ihomes.title
    .interviews__title2
      = ihomes.title2

  .sectionboxG__grid__down

  
-# .price__type
-#   - ihomes.iihomes.each_with_index do |i,t|
-#     .ihomes_t{class:"price__patarnA#{t}"}
-#       .patarnAL__title
-#         = i.title
-#       .patarnAL__discribe
-#         = i.discribe
-#       .patarnAL__features
-#         .ihomes_t1{class:"patarnAL__features__#{t}"}
-#           = i.colum1
-#         .ihomes_t1{class:"patarnAL__features__#{t}"}
-#           = i.colum2
-#         .ihomes_t1{class:"patarnAL__features__#{t}"}
-#           = i.colum3
-#       .patarnAL__price
-#         = i.price
.planning
  .planing__grid
    - ihomes.iihomes.each_with_index do |i,t|
      .planing__grid__box
        .planning__image.playzoon{"data-youtube_id" => "#{i.id}"}
          - if i.image?
            = link_to iihomes_youtube_path() do
              = image_tag i.image.url
              .planning__players
                = icon("far","play-circle",class:"players")
        .planning__price
          = i.price
        .planning__title
          = i.title

app/views/ihomes/_iihome_fields.html.haml
.nested-fields
  .field
    .aformd__title
      .formtitles
        = f.label :image
      = f.file_field :image, accept:"image/jpeg,image/png"

    .aformd__title
      .formtitles
        = f.label :youtube
      = f.text_field :youtube,class:"aformd"
    .aformd__title
      .formtitles
        = f.label :price
      = f.text_field :price,class:"aformd"
    .aformd__title
      .formtitles
        = f.label :title
      = f.text_field :title,class:"aformd"
.nested-fields__button2
  = f.label '削除',class:"desvv2" do
    削除
    = f.check_box :_destroy,class:"desvv2"

app/views/ihomes/_smafo_ihomes.html.haml
.sectionboxG__grid
  .sectionboxG__grid__up

    .price__discribe
      = ihomes.title
      %br
      = ihomes.title2
      %br
      = ihomes.title3
  .sectionboxG__grid__down

  
-# .price__type
-#   - ihomes.iihomes.each_with_index do |i,t|
-#     .ihomes_t{class:"price__patarnA#{t}"}
-#       .patarnAL__title
-#         = i.title
-#       .patarnAL__discribe
-#         = i.discribe
-#       .patarnAL__features
-#         .ihomes_t1{class:"patarnAL__features__#{t}"}
-#           = i.colum1
-#         .ihomes_t1{class:"patarnAL__features__#{t}"}
-#           = i.colum2
-#         .ihomes_t1{class:"patarnAL__features__#{t}"}
-#           = i.colum3
-#       .patarnAL__price
-#         = i.price
.planning
  .planing__grid
    - ihomes.iihomes.each_with_index do |i,t|
      .planing__grid__box
        .planning__image{"data-youtube_id" => "#{i.id}"}
          .movie-wrap
            %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/#{i.youtube.last(11)}", :width => "560"}
          -# - if i.image?
          -#   = link_to iihomes_youtube_path() do
          -#     = image_tag i.image.url
          -#     .planning__players
          -#       = icon("far","play-circle",class:"players")
        .planning__price
          = i.price
        .planning__title
          = i.title

app/views/ihomes/update.js.erb
$('#ihomes__rendering').html("<%= j(render partial: 'ihomes/ihomes', locals: {ihomes: @ihomes}) %>");
$('#ihomes_area--box3-<%= @ihomes.id %>').html("<%= j(render partial: 'ihomes/admins_ihomes', locals: {ihomes: @ihomes}) %>");


$('#ihomes_area--box3-<%= @ihomes.id %>').hide();
$('#icr-edit-button<%= @ihomes.id %>').hide;
  $(".allcover__sheet").css("display","none");
$('#alert-message').html('<div class="alert alert-success"><%= @msg %></div>')

$("#alert-message").fadeIn().queue(function() {
            setTimeout(function(){$("#alert-message").dequeue();
            }, 5000);
        });

        $("#alert-message").fadeOut();