config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'homes#index'
  resources :homes, only:[:index]
    namespace :admin do
      resources :homes, only: [:index, :new, :create, :show,  :edit, :update, :destroy]
  end


  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'   
} 

# root  'inquiry#index'
  # get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiries/confirm' => 'inquiries#confirm'   # 確認画面
  post  'inquiries/back' => 'inquiries#back'   # 確認画面
  post  'inquiries/thanks'  => 'inquiries#thanks'    # 送信完了画面

  get  'iihomes/youtube'  => 'iihomes#youtube'    # 送信完了画面
  get  'eehomes/youtube'  => 'eehomes#youtube'    # 送信完了画面



# resources :users, :only => [:show]

resource :ahomes, only:[:edit,:update]

resource :bhomes, only:[:edit,:update]

resource :chomes, only:[:edit,:update]

resource :dhomes, only:[:edit,:update]

resource :ehomes, only:[:update]

resource :ehomes, only:[:new,:create,:update]

resource :fhomes, only:[:update]

resource :ihomes, only:[:update] 


  

resource :contacts, only:[:update]

resource :interviews, only:[:update]


resource :blogs, only:[:new,:create,:destroy,:update]

# devise_scope :user do
#   get "user/:id", :to => "users/registrations#detail"
#   get "signup", :to => "users/registrations#new"
#   get "login", :to => "users/sessions#new"
#   get "logout", :to => "users/sessions#destroy"
# end

end

app/models/aahome.rb
class Aahome < ApplicationRecord
  belongs_to :ahome
  
end

app/models/ahome.rb
class Ahome < ApplicationRecord
  has_many :aahomes
  accepts_nested_attributes_for :aahomes,allow_destroy: true
  mount_uploader :logo, ImageUploader
end

app/models/bbhome.rb
class Bbhome < ApplicationRecord
  belongs_to :bhome
  mount_uploader :image, ImageUploader
end

app/models/bhome.rb
class Bhome < ApplicationRecord
  has_many :bbhomes
  accepts_nested_attributes_for :bbhomes,allow_destroy: true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_rich_text :content
  mount_uploader :image, ImageUploader
end

app/models/chome.rb
class Chome < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/dhome.rb
class Dhome < ApplicationRecord
end

app/models/eehome.rb
class Eehome < ApplicationRecord
  belongs_to :ehome
  # mount_uploader :image, VideoUploader
  mount_uploader :image, ImageUploader

end

app/models/ehome.rb
class Ehome < ApplicationRecord
  has_many :eehomes
  accepts_nested_attributes_for :eehomes,allow_destroy: true
end

app/models/ffhome.rb
class Ffhome < ApplicationRecord
  belongs_to :fhome
end

app/models/fhome.rb
class Fhome < ApplicationRecord
  has_many :ffhomes
  accepts_nested_attributes_for :ffhomes,allow_destroy: true
end

app/models/home.rb
class Home < ApplicationRecord
  has_many :interviews
  accepts_nested_attributes_for :interviews,allow_destroy: true
end

app/models/ihome.rb
class Ihome < ApplicationRecord
  has_many :iihomes
  accepts_nested_attributes_for :iihomes,allow_destroy: true
end

app/models/iihome.rb
class Iihome < ApplicationRecord
  belongs_to :ihome
  mount_uploader :image, ImageUploader
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  # attr_accessor :name, :email, :message

  validates :name,presence: { :message => 'ご担当者様名を入力してください。'}
  validates :email,presence: { :message => 'E-mailを入力してください。'}
  validates :message,presence: { :message => 'お問い合わせ内容を入力してください'}
end

app/models/interview.rb
class Interview < ApplicationRecord
  belongs_to :home
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # devise :database_authenticatable, :rememberable, :validatable
end

app/controllers/ehomes_controller.rb
class EhomesController < ApplicationController
  before_action :if_not_admin
  
  def update
    @ehomes = Ehome.find(1)
    # @url = params[:ehome][:eehomes][:youtube_url]
    
    # @bbhomes = @bhomes.bbhomes
    @msg = "アップデートが完了しました。"
    @ehomes.update(ehomes_params)
    # if @ehomes.save
    #   redirect_to request.referer
    # else
    #   render :new
    # end
  end

  private 
  def if_not_admin
    if user_signed_in?
      redirect_to root_path unless current_user.admin?
    else
      redirect_to root_path
    end
  end

  def ehomes_params 

      
      params.require(:ehome).permit(:title,:discribe,eehomes_attributes:[:title,:discribe,:youtube,:image, :id ,:_destroy])

      # params.require(:ehome).permit(:title,:discribe,eehomes_attributes:[:title,:discribe,:youtube, :id ,:_destroy])
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/ehomes_helper.rb
module EhomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ehomes/_admins_ehomes.html.haml
.ahomes_secondary
  fourthPageの編集

=form_with model: ehomes,url:ehomes_path,method: :patch, remote:true do |f|
  .ahomes__form
    .ahomes__title.aformd__title
      .formtitles
        １つ目のタイトル
      = f.text_field :title, class: "ehomes__title__field aformd",autocomplete: "off",placeholder:"上段のタイトルを入力してください",id:"js-ehome-edit-#{ehomes.id}"
    .ahomes__title2.aformd__title
      .formtitles
        詳細
      
      = f.text_field :discribe, class: "ehomes__title2__field aformd",autocomplete: "off",placeholder:"下段のタイトルを入力してください",id:"js-ehome-edit-#{ehomes.id}"
    
  = f.fields_for :eehomes do |c|       
    .form-group
      = render 'eehome_fields', f: c
  .links.nested-fields__button2
    = link_to_add_association '追加する' ,f, :eehomes
      
    
  .ahomes__submit
    = f.submit "更新",class:"aformd__submit"

.ecr-edit-button.aformd__edit__button{id: "ecr-edit-button#{ehomes.id}", :style => "display: none;"}
  .aaaaa.ecr-cancel-button{"data-cancel-ide" => "#{ehomes.id}"}
    = icon("far","times-circle")

app/views/ehomes/_eehome_fields.html.haml
.nested-fields
  .field
    .aformd__title
      .formtitles
        = f.label :title
      = f.text_field :title, class:"aformd"
    .aformd__title
      .formtitles
        = f.label :discribe
      = f.text_area :discribe, class:"aformd"

    .aformd__title
      .formtitles
        youtube_url
      = f.text_field :youtube, class:"aformd"
    
    .aformd__title
      .formtitles
        thumbnail
      = f.file_field :image, class:"aformd"
    
    -# .aformd__title
    -#   .formtitles
    -#     thumbnail
    -#   = f.file_field :poster,accept:"image/jpeg,image/png", class:"aformd"
    -# .aformd__title
    -#   .formtitles
    -#     video
    -#   = f.file_field :image, accept:"video/mp4",class:"aformd"
.nested-fields__button2
  -# = link_to_remove_association "削除", f,class: "desvv2"
  = f.label '削除',class:"desvv2" do
 
    削除
    = f.check_box :_destroy,class:"desvv2"
    

app/views/ehomes/_ehomes.html.haml
.services.ShareContainer.emghj
  .SectionBoxB#serlechs
    .services__container2.ShareRows
      = ehomes.title
    .services__container2.ShareRows2
      = ehomes.discribe
-# .SectionBoxC
-#   .swiper-container2
-#     / Additional required wrapper
-#     .swiper-wrapper
-#       / Slides
-#       -ehomes.eehomes.each do |e|
-#         .swiper-slide
-#           .sectionboxE
-#             .S2__image
-#               - if e.youtube?
-#                 -#mp4下
-#                 -# = video_tag(e.image.url, muted: :true,controls: :true,poster:"#{e.poster}",controlslist: :nodownload)

-#                 %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/#{e.youtube.last(11)}", :width => "560"}

                  
-#             .sectionboxEA
-#               .S2__company
-#                 = e.title
-#               .S2__discribe
-#                 = e.discribe
      
-# %script{:src => "https://unpkg.com/swiper/swiper-bundle.js"}
-# %script{:src => "https://unpkg.com/swiper/swiper-bundle.min.js"}
-# = javascript_pack_tag "swiper/swiper2.js"
-# .planning
-#   .planing__grid
-#     - ehomes.eehomes.each_with_index do |i,t|
-#       .planing__grid__box
-#         .planning__image.playzoon2{"data-youtube_id2" => "#{i.id}"}
-#           - if i.image?
-#             = link_to eehomes_youtube_path() do
-#               = image_tag i.image.url
-#               .planning__players
-#                 = icon("far","play-circle",class:"players")
-#         .planning__price
-#           = i.discribe
-#         .planning__title
-#           = i.title


.planning
  .swiper-container2.planing__grid__uti
    .swiper-wrapper
      - ehomes.eehomes.each_with_index do |i,t|
        .swiper-slide
          .planing__grid.milkkandy__box__service
            .planing__grid__box
              .planning__image.playzoon2{"data-youtube_id2" => "#{i.id}"}
                - if i.image?
                  = link_to eehomes_youtube_path() do
                    = image_tag i.image.url
                    .planning__players
                      = icon("far","play-circle",class:"players")
              .planning__price.planning__price2
              
                = safe_join(i.discribe.split("\n"),tag(:br))
              .planning__title
                = i.title

-# %script{:src => "https://unpkg.com/swiper/swiper-bundle.js"}
-# %script{:src => "https://unpkg.com/swiper/swiper-bundle.min.js"}
-# = javascript_pack_tag "swiper/swiper2.js", media: 'all', 'data-turbolinks-track': 'reload'
= javascript_pack_tag "swiper/swiper2.js"

   

app/views/ehomes/_smafo_ehomes.html.haml
.services.ShareContainer.emghj
  .SectionBoxB#serlechs
    .services__container2.ShareRows
      = ehomes.title
    .services__container2.ShareRows2
      = ehomes.discribe

.planning
  .swiper-container2.planing__grid__uti
    .swiper-wrapper
      - ehomes.eehomes.each_with_index do |i,t|
        .swiper-slide
          .planing__grid.milkkandy__box__service
            .planing__grid__box
              .planning__image{"data-youtube_id2" => "#{i.id}"}
                .movie-wrap
                  %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/#{i.youtube.last(11)}", :width => "560"}
              .planning__price.planning__price2
                = i.discribe
              .planning__title
                = i.title

-# %script{:src => "https://unpkg.com/swiper/swiper-bundle.js"}
-# %script{:src => "https://unpkg.com/swiper/swiper-bundle.min.js"}
= javascript_pack_tag "swiper/swiper2.js", media: 'all', 'data-turbolinks-track': 'reload'

app/views/ehomes/update.js.erb
$('#ehomes__rendering').html("<%= j(render partial: 'ehomes/ehomes', locals: {ehomes: @ehomes}) %>");
$('#ehomes_area--box3-<%= @ehomes.id %>').html("<%= j(render partial: 'ehomes/admins_ehomes', locals: {ehomes: @ehomes}) %>");


$('#ehomes_area--box3-<%= @ehomes.id %>').hide();
$('#ecr-edit-button<%= @ehomes.id %>').hide;
  $(".allcover__sheet").css("display","none");
$('#alert-message').html('<div class="alert alert-success"><%= @msg %></div>')

$("#alert-message").fadeIn().queue(function() {
            setTimeout(function(){$("#alert-message").dequeue();
            }, 5000);
        });

        $("#alert-message").fadeOut();