config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'homes#index'
  resources :homes, only:[:index]
    namespace :admin do
      resources :homes, only: [:index, :new, :create, :show,  :edit, :update, :destroy]
  end


  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'   
} 

# root  'inquiry#index'
  # get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiries/confirm' => 'inquiries#confirm'   # 確認画面
  post  'inquiries/back' => 'inquiries#back'   # 確認画面
  post  'inquiries/thanks'  => 'inquiries#thanks'    # 送信完了画面

  get  'iihomes/youtube'  => 'iihomes#youtube'    # 送信完了画面
  get  'eehomes/youtube'  => 'eehomes#youtube'    # 送信完了画面



# resources :users, :only => [:show]

resource :ahomes, only:[:edit,:update]

resource :bhomes, only:[:edit,:update]

resource :chomes, only:[:edit,:update]

resource :dhomes, only:[:edit,:update]

resource :ehomes, only:[:update]

resource :ehomes, only:[:new,:create,:update]

resource :fhomes, only:[:update]

resource :ihomes, only:[:update] 


  

resource :contacts, only:[:update]

resource :interviews, only:[:update]


resource :blogs, only:[:new,:create,:destroy,:update]

# devise_scope :user do
#   get "user/:id", :to => "users/registrations#detail"
#   get "signup", :to => "users/registrations#new"
#   get "login", :to => "users/sessions#new"
#   get "logout", :to => "users/sessions#destroy"
# end

end

app/models/aahome.rb
class Aahome < ApplicationRecord
  belongs_to :ahome
  
end

app/models/ahome.rb
class Ahome < ApplicationRecord
  has_many :aahomes
  accepts_nested_attributes_for :aahomes,allow_destroy: true
  mount_uploader :logo, ImageUploader
end

app/models/bbhome.rb
class Bbhome < ApplicationRecord
  belongs_to :bhome
  mount_uploader :image, ImageUploader
end

app/models/bhome.rb
class Bhome < ApplicationRecord
  has_many :bbhomes
  accepts_nested_attributes_for :bbhomes,allow_destroy: true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_rich_text :content
  mount_uploader :image, ImageUploader
end

app/models/chome.rb
class Chome < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/dhome.rb
class Dhome < ApplicationRecord
end

app/models/eehome.rb
class Eehome < ApplicationRecord
  belongs_to :ehome
  # mount_uploader :image, VideoUploader
  mount_uploader :image, ImageUploader

end

app/models/ehome.rb
class Ehome < ApplicationRecord
  has_many :eehomes
  accepts_nested_attributes_for :eehomes,allow_destroy: true
end

app/models/ffhome.rb
class Ffhome < ApplicationRecord
  belongs_to :fhome
end

app/models/fhome.rb
class Fhome < ApplicationRecord
  has_many :ffhomes
  accepts_nested_attributes_for :ffhomes,allow_destroy: true
end

app/models/home.rb
class Home < ApplicationRecord
  has_many :interviews
  accepts_nested_attributes_for :interviews,allow_destroy: true
end

app/models/ihome.rb
class Ihome < ApplicationRecord
  has_many :iihomes
  accepts_nested_attributes_for :iihomes,allow_destroy: true
end

app/models/iihome.rb
class Iihome < ApplicationRecord
  belongs_to :ihome
  mount_uploader :image, ImageUploader
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  # attr_accessor :name, :email, :message

  validates :name,presence: { :message => 'ご担当者様名を入力してください。'}
  validates :email,presence: { :message => 'E-mailを入力してください。'}
  validates :message,presence: { :message => 'お問い合わせ内容を入力してください'}
end

app/models/interview.rb
class Interview < ApplicationRecord
  belongs_to :home
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # devise :database_authenticatable, :rememberable, :validatable
end

app/controllers/bhomes_controller.rb
class BhomesController < ApplicationController
  def edit
    @bhomes = Bhome.find(params[:id])
    @bbhomes = @bhomes.bbhomes

  end

  def update
    @msg = "アップデートが完了しました。"
    @bhomes = Bhome.find(params[:id])
    # @bbhomes = @bhomes.bbhomes
    @bhomes.update(bhomes_params)

    # if @bhomes.save
    #   redirect_to request.referer
    # else
    #   render :new
    # end
  end

  private 
  def if_not_admin
    if user_signed_in?
      redirect_to root_path unless current_user.admin?
    else
      redirect_to root_path
    end
  end

  def bhomes_params 


      # params.require(:bhome).permit(:title,:title2,:discribe,bbhomes_attributes:[:title,:discribe,:id])
      params.require(:bhome).permit(:title,:title2,:discribe,bbhomes_attributes:[:title,:discribe,:image,:id])


  
  
  end
end

app/helpers/bhomes_helper.rb
module BhomesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bhomes/_admins_bhomes.html.haml
.ahomes_secondary
  SecondPageの編集
  
  -# =form_with url: bhomes_path(@bhomes.id),method: :patch,remote:true do |f|
  -# =form_with model:Bhome.find(1),remote:true do |f|
=form_with model: bhomes,url:bhomes_path(id:bhomes.id),method: :patch, remote:true do |f|
  .ahomes__form
    .ahomes__title.aformd__title
      .formtitles
        上段のタイトル
      = f.text_field :title, class: "bhomes__title__field aformd",autocomplete: "off",placeholder:"上段のタイトルを入力してください",id:"js-ahome-edit-#{bhomes.id}"
    .ahomes__title2.aformd__title
      .formtitles
        下段のタイトル
      = f.text_field :title2, class: "bhomes__title2__field aformd",autocomplete: "off",placeholder:"下段のタイトルを入力してください",id:"js-ahome-edit-#{bhomes.id}"
    .ahomes__title2.aformd__title
      .formtitles
        詳細
      
      = f.text_field :discribe, class: "bhomes__title2__field aformd",autocomplete: "off",placeholder:"下段のタイトルを入力してください",id:"js-ahome-edit-#{bhomes.id}"

    -# - @bhomes.bbhomes.each do |d|
    = f.fields_for :bbhomes do |c|
      -# = render "bbhomes_fields", f: c
      -# - @bhomes.bbhomes.each do |d|
      .form-group
        .aformd__title
          .formtitles
            = c.label :image
            = c.file_field :image, accept:"image/jpeg,image/png"
          .formtitles
            = c.label :title
          = c.text_field :title,class:"aformd"
          .formtitles
            = c.label :discribe
          = c.text_field :discribe,class:"aformd"
    -#     = c.label :discribe
    -#     = c.text_field :discribe
    
    
    
  .ahomes__submit
    = f.submit "更新",class:"aformd__submit"

.bcr-edit-button.aformd__edit__button{id: "bcr-edit-button#{bhomes.id}", :style => "display: none;"}
  .aaaaa.bcr-cancel-button{"data-cancel-idb" => "#{bhomes.id}"}
    =icon("far","times-circle")

app/views/bhomes/_bhomes.html.haml
.services.ShareContainer{id: "bhomes_area--box2b"}
  -# .SectionBoxB
  -#   .services__container.ShareRows
  -#     =bhomes.title
  -#     %br
  -#     =bhomes.title2
  -#   .services__container2.ShareRows2
  -#     =bhomes.discribe

  .interviews__ibox
    .interviews__title
      = bhomes.title
    .interviews__title2
      = bhomes.title2
-# .SectionBoxC{id: "bhomes_area--box2bb"}
-#   .swiper-container
-#     / Additional required wrapper
-#     .swiper-wrapper
-#       / Slides
-#       - bhomes.bbhomes.each_with_index do |b,i|
-#         - i = i + 1
-#         .swiper-slide 
-#           .sectionboxD
-#             .S__logo
-#               = i
-#             .S__title
-#               =b.title
-#             .S__discribe
-#               =b.discribe
      
          
-#     / If we need pagination
-#     .swiper-pagination
      
-#     / If we need navigation buttons
-#     .swiper-button-prev
-#       -# =icon("fas","chevron-circle-left",class:"mikan")

      
-#       -# = icon("fas","search",class: "mikan")
-#     .swiper-button-next
-#       -# = icon("fas","chevron-circle-right",class: "mikan")

-# %script{:src => "https://unpkg.com/swiper/swiper-bundle.js"}
-# %script{:src => "https://unpkg.com/swiper/swiper-bundle.min.js"}
-# = javascript_pack_tag "swiper/swiper.js"

.SectionBoxC{id: "bhomes_area--box2bb"}
  .new__service__grid__row
    - bhomes.bbhomes.each do |b|
      .new__servuce__girid__row__box
        .new__service__images
          - if b.image?
            = image_tag b.image.url
        .new__service__title
          = b.title
        .new__service__discribe
          = b.discribe

app/views/bhomes/update.js.erb
$('#bbc').html("<%= j(render partial: 'bhomes/bhomes', locals: {bhomes: @bhomes}) %>");
$('#bhomes_area--box3-<%= @bhomes.id %>').html("<%= j(render partial: 'bhomes/admins_bhomes', locals: {bhomes: @bhomes}) %>");



$('#bhomes_area--box3-<%= @bhomes.id %>').hide();
$('#bcr-edit-button<%= @bhomes.id %>').hide;
  $(".allcover__sheet").css("display","none");
$('#alert-message').html('<div class="alert alert-success"><%= @msg %></div>')

$("#alert-message").fadeIn().queue(function() {
            setTimeout(function(){$("#alert-message").dequeue();
            }, 5000);
        });

        $("#alert-message").fadeOut();